### ISSUE TITLE
Task 별 submission 

### ISSUE THREAD

**Issue by Jihyun22** [KLUE-benchmark/KLUE-baseline#2]
## What's your idea? 🤔

안녕하세요, 이렇게 klue benchmark 에 대한 pipeline 공개해주셔서 감사합니다.
다름이 아니라, fine tuning 결과를 test set 으로도 평가해보고 싶은데, KLUE [공식 페이지](https://klue-benchmark.com/tasks) 에 submission 하는 형식이 어떻게 되나요 ?
우선 `output_dir` 자체를 `tar -czvf submission.tar.gz [output_dir]` 로 압축하고 있는데, 계속 fail 이 떠서 log 를 살펴보고 있습니다. checkpoint 만 따로 묶어 두어야 하는지, 혹은 다른 방법이 있는지 궁금합니다.

감사합니다.

**Comment by inmoonlight** [comment]
@Jihyun22 안녕하세요, 문의 감사드립니다.

https://aistages-prod-server-public.s3.amazonaws.com/app/Competitions/000065/data/klue_code.tar.gz 에 제공된 baseline code 를 보고 참고하셔서 같은 형식으로 제출하시면 좋을 것 같습니다.

그리고 앞으로 이슈는 https://github.com/KLUE-benchmark/KLUE 으로 남겨주시면 좋을 것 같습니다. 감사합니다

**Comment by Jihyun22** [comment]
> @Jihyun22 안녕하세요, 문의 감사드립니다.
> 
> https://aistages-prod-server-public.s3.amazonaws.com/app/Competitions/000065/data/klue_code.tar.gz 에 제공된 baseline code 를 보고 참고하셔서 같은 형식으로 제출하시면 좋을 것 같습니다.
> 
> 그리고 앞으로 이슈는 https://github.com/KLUE-benchmark/KLUE 으로 남겨주시면 좋을 것 같습니다. 감사합니다

넵 감사합니다 좋은 하루 되세요 ~
